module.exports = `
    type ActivePlayerStats {
        _id: ID
        sessionId: ActiveSession
        user: User
        FGS: Int
        PTS: Int
        TPM: Int
        REB: Int
        BLK: Int
        STL: Int
    }
`;